// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates prompts for the "Caption This!" game.
 *
 * - generateCaptionImagePrompt - A function that generates a prompt for an image to be captioned.
 * - GenerateCaptionImagePromptInput - The input type for the generateCaptionImagePrompt function.
 * - GenerateCaptionImagePromptOutput - The return type for the generateCaptionImagePrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCaptionImagePromptInputSchema = z.object({
  topic: z.string().optional().describe('Optional topic for the image prompt.'),
});
export type GenerateCaptionImagePromptInput = z.infer<
  typeof GenerateCaptionImagePromptInputSchema
>;

const GenerateCaptionImagePromptOutputSchema = z.object({
  prompt: z.string().describe('A prompt for a weird, funny, or interesting image.'),
});
export type GenerateCaptionImagePromptOutput = z.infer<
  typeof GenerateCaptionImagePromptOutputSchema
>;

export async function generateCaptionImagePrompt(
  input: GenerateCaptionImagePromptInput
): Promise<GenerateCaptionImagePromptOutput> {
  return generateCaptionImagePromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCaptionImagePrompt',
  input: {schema: GenerateCaptionImagePromptInputSchema},
  output: {schema: GenerateCaptionImagePromptOutputSchema},
  prompt: `You are a creative assistant. Your task is to generate a descriptive prompt for an image that would be funny, weird, or interesting to caption. The prompt should be for an AI image generator.

  Example: "A photo of a cat wearing a tiny astronaut helmet, looking surprised."
  Example: "An oil painting of a giraffe playing chess with a flamingo in a library."
  
  {{#if topic}}
  The prompt should be related to the topic of: {{{topic}}}.
  {{/if}}

  Generate one prompt.`,
});

const generateCaptionImagePromptFlow = ai.defineFlow(
  {
    name: 'generateCaptionImagePromptFlow',
    inputSchema: GenerateCaptionImagePromptInputSchema,
    outputSchema: GenerateCaptionImagePromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
