// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates "Would You Rather?" questions.
 *
 * - generateWouldYouRather - A function that generates a "Would You Rather?" question.
 * - GenerateWouldYouRatherInput - The input type for the generateWouldYouRather function.
 * - GenerateWouldYouRatherOutput - The return type for the generateWouldYouRather function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateWouldYouRatherInputSchema = z.object({});
export type GenerateWouldYouRatherInput = z.infer<
  typeof GenerateWouldYouRatherInputSchema
>;

const GenerateWouldYouRatherOutputSchema = z.object({
  optionA: z.string().describe('The first option for the "Would You Rather?" question.'),
  optionB: z.string().describe('The second option for the "Would You Rather?" question.'),
});
export type GenerateWouldYouRatherOutput = z.infer<
  typeof GenerateWouldYouRatherOutputSchema
>;

export async function generateWouldYouRather(
  input: GenerateWouldYouRatherInput
): Promise<GenerateWouldYouRatherOutput> {
  return generateWouldYouRatherFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateWouldYouRatherPrompt',
  input: {schema: GenerateWouldYouRatherInputSchema},
  output: {schema: GenerateWouldYouRatherOutputSchema},
  prompt: `You are a creative assistant that generates "Would You Rather?" questions for college freshers to break the ice. The questions should be fun, engaging, and appropriate for a college setting.

  Generate one "Would You Rather?" question with two options.`,
});

const generateWouldYouRatherFlow = ai.defineFlow(
  {
    name: 'generateWouldYouRatherFlow',
    inputSchema: GenerateWouldYouRatherInputSchema,
    outputSchema: GenerateWouldYouRatherOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
