// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates prompts for a game of Charades.
 *
 * - generateCharadesPrompt - A function that generates a prompt for a player to act out.
 * - GenerateCharadesPromptInput - The input type for the generateCharadesPrompt function.
 * - GenerateCharadesPromptOutput - The return type for the generateCharadesPrompt function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCharadesPromptInputSchema = z.object({
  topic: z.string().optional().describe('Optional topic for the charades prompt (e.g., "Movies", "Animals", "Everyday Activities").'),
});
export type GenerateCharadesPromptInput = z.infer<
  typeof GenerateCharadesPromptInputSchema
>;

const GenerateCharadesPromptOutputSchema = z.object({
  prompt: z.string().describe('The prompt for the player to act out. This should be a person, place, thing, or action.'),
  category: z.string().describe('The category of the prompt (e.g., Movie, Animal, Object, Action).'),
});
export type GenerateCharadesPromptOutput = z.infer<
  typeof GenerateCharadesPromptOutputSchema
>;

export async function generateCharadesPrompt(
  input: GenerateCharadesPromptInput
): Promise<GenerateCharadesPromptOutput> {
  return generateCharadesPromptFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateCharadesPrompt',
  input: {schema: GenerateCharadesPromptInputSchema},
  output: {schema: GenerateCharadesPromptOutputSchema},
  prompt: `You are a creative game master. Your task is to generate a prompt for a game of Charades, suitable for college students. The prompt should be a person, place, thing, or action that is fun to act out. It should not be too easy or too difficult.

  Examples:
  - Prompt: "Baking a cake", Category: "Action"
  - Prompt: "Harry Potter", Category: "Movie Character"
  - Prompt: "Playing the air guitar", Category: "Action"
  - Prompt: "A T-Rex trying to make a bed", Category: "Silly Action"
  
  {{#if topic}}
  The prompt should be related to the topic of: {{{topic}}}.
  {{/if}}

  Generate one prompt.`,
});

const generateCharadesPromptFlow = ai.defineFlow(
  {
    name: 'generateCharadesPromptFlow',
    inputSchema: GenerateCharadesPromptInputSchema,
    outputSchema: GenerateCharadesPromptOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
