// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates "Who's Most Likely To..." questions.
 *
 * - generateMostLikelyTo - A function that generates a "Who's Most Likely To..." question.
 * - GenerateMostLikelyToInput - The input type for the generateMostLikelyTo function.
 * - GenerateMostLikelyToOutput - The return type for the generateMostLikelyTo function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateMostLikelyToInputSchema = z.object({});
export type GenerateMostLikelyToInput = z.infer<
  typeof GenerateMostLikelyToInputSchema
>;

const GenerateMostLikelyToOutputSchema = z.object({
  question: z.string().describe('The "Who\'s Most Likely To..." question.'),
});
export type GenerateMostLikelyToOutput = z.infer<
  typeof GenerateMostLikelyToOutputSchema
>;

export async function generateMostLikelyTo(
  input: GenerateMostLikelyToInput
): Promise<GenerateMostLikelyToOutput> {
  return generateMostLikelyToFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMostLikelyToPrompt',
  input: {schema: GenerateMostLikelyToInputSchema},
  output: {schema: GenerateMostLikelyToOutputSchema},
  prompt: `You are a creative assistant that generates "Who's Most Likely To..." questions for college freshers to break the ice. The questions should be funny, relatable, and appropriate for a college setting.

  Generate one "Who's Most Likely To..." question. The question should not include the phrase "Who's most likely to".
  For example, instead of "Who's most likely to win a Nobel prize?", output "win a Nobel prize?".
  `,
});

const generateMostLikelyToFlow = ai.defineFlow(
  {
    name: 'generateMostLikelyToFlow',
    inputSchema: GenerateMostLikelyToInputSchema,
    outputSchema: GenerateMostLikelyToOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
