// This is an autogenerated file from Firebase Studio.
"use client";

import { WouldYouRatherGenerator } from "@/components/would-you-rather-generator";
import { ActivityPageLayout } from "@/components/activity-page-layout";

export default function WouldYouRatherPage() {
  return (
    <ActivityPageLayout
      title="Would You Rather"
      description="Make a tough choice between two fun, tricky, or downright weird scenarios!"
    >
      <WouldYouRatherGenerator />
    </ActivityPageLayout>
  );
}
