// This is an autogenerated file from Firebase Studio.
"use client";

import { MostLikelyToGenerator } from "@/components/most-likely-to-generator";
import { ActivityPageLayout } from "@/components/activity-page-layout";

export default function MostLikelyToPage() {
  return (
    <ActivityPageLayout
      title="Who's Most Likely To..."
      description="A fun game to see who in your group fits the bill. Point, laugh, and get to know each other!"
    >
      <MostLikelyToGenerator />
    </ActivityPageLayout>
  );
}
