// This is an autogenerated file from Firebase Studio.
"use client";

import { CaptionThisGenerator } from "@/components/caption-this-generator";
import { ActivityPageLayout } from "@/components/activity-page-layout";

export default function CaptionThisPage() {
  return (
    <ActivityPageLayout
      title="Caption This!"
      description="Get your creative juices flowing. Come up with a funny or clever caption for the AI-generated image!"
    >
      <CaptionThisGenerator />
    </ActivityPageLayout>
  );
}
