// This is an autogenerated file from Firebase Studio.
"use client";

import { useState } from "react";
import { generateMostLikelyTo, type GenerateMostLikelyToOutput } from "@/ai/flows/generate-most-likely-to";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Loader2, Users } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export function MostLikelyToGenerator() {
  const [data, setData] = useState<GenerateMostLikelyToOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsLoading(true);
    setData(null);
    try {
      const result = await generateMostLikelyTo({});
      setData(result);
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Error Generating Question",
        description: "Could not generate a question. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="space-y-6 text-center">
      <Button onClick={handleGenerate} disabled={isLoading} className="w-full text-lg py-6">
        {isLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : "Generate New Scenario"}
      </Button>

      {data ? (
        <Card className="bg-primary/10 border-primary/20 shadow-xl transition-all duration-500 ease-out animate-in fade-in zoom-in-95">
          <CardContent className="p-8">
            <h2 className="text-3xl font-bold text-primary tracking-tight">Who's most likely to...</h2>
            <p className="mt-4 text-2xl font-medium text-foreground">{data.question}</p>
          </CardContent>
        </Card>
      ) : (
         <div className="flex flex-col items-center justify-center p-8 text-center bg-card rounded-xl">
            <Users className="w-24 h-24 text-primary/20" />
            <p className="mt-4 text-lg text-muted-foreground">Click the button to start the game!</p>
        </div>
      )}
    </div>
  );
}
