// This is an autogenerated file from Firebase Studio.
"use client";

import { useState } from "react";
import { generateWouldYouRather, type GenerateWouldYouRatherOutput } from "@/ai/flows/generate-would-you-rather";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";

export function WouldYouRatherGenerator() {
  const [data, setData] = useState<GenerateWouldYouRatherOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedOption, setSelectedOption] = useState<"A" | "B" | null>(null);
  const { toast } = useToast();

  const handleGenerate = async () => {
    setIsLoading(true);
    setData(null);
    setSelectedOption(null);
    try {
      const result = await generateWouldYouRather({});
      setData(result);
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Error Generating Question",
        description: "Could not generate a question. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleSelectOption = (option: "A" | "B") => {
    setSelectedOption(option);
  };

  const getCardClasses = (option: "A" | "B") => {
    return cn(
      "cursor-pointer transition-all duration-300 ease-in-out hover:shadow-lg",
      selectedOption === null ? "hover:scale-105" : "",
      selectedOption === option ? "scale-105 bg-primary/20 border-primary shadow-xl" : "",
      selectedOption !== null && selectedOption !== option ? "opacity-50 scale-95" : ""
    );
  };

  return (
    <div className="space-y-6">
      <Button onClick={handleGenerate} disabled={isLoading} className="w-full text-lg py-6">
        {isLoading ? <Loader2 className="h-6 w-6 animate-spin" /> : "Generate New Question"}
      </Button>

      {data && (
        <div className="space-y-4 text-center">
            <h2 className="text-2xl font-bold text-primary">Would You Rather...</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 items-stretch">
                <Card className={getCardClasses("A")} onClick={() => handleSelectOption("A")}>
                    <CardContent className="p-6 text-xl font-medium flex items-center justify-center h-full">
                        <p>{data.optionA}</p>
                    </CardContent>
                </Card>

                <div className="flex items-center justify-center">
                    <p className="text-2xl font-bold text-muted-foreground">OR</p>
                </div>

                <Card className={getCardClasses("B")} onClick={() => handleSelectOption("B")}>
                     <CardContent className="p-6 text-xl font-medium flex items-center justify-center h-full">
                        <p>{data.optionB}</p>
                    </CardContent>
                </Card>
            </div>
        </div>
      )}
    </div>
  );
}
