// This is an autogenerated file from Firebase Studio.
"use client";

import { CharadesGenerator } from "@/components/charades-generator";
import { ActivityPageLayout } from "@/components/activity-page-layout";

export default function CharadesPage() {
  return (
    <ActivityPageLayout
      title="Charades with AI"
      description="Time to act it out! Get a prompt from the AI and have your friends guess what it is. No talking allowed!"
    >
      <CharadesGenerator />
    </ActivityPageLayout>
  );
}
